version: '3'
services:
  task_app:
    container_name: task-app
    build: .
    restart: always
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_db
      SPRING_DATASOURCE_USERNAME: task
      SPRING_DATASOURCE_PASSWORD: task_pw
    links:
      - postgres
  postgres:
    container_name: postgres-db
    image: "postgres:15"
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: task
      POSTGRES_PASSWORD: task_pw
