spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/task_db
        username: task
        password: task_pw
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database: postgresql
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
        tryItOutEnabled: true
        filter: true
        tagsSorter: alpha
    api-docs:
        path: /v3/api-docs
        enabled: true
server:
    port: 8083

logging:
        pattern:
            file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file:
            name: logs.log
        level:
            org.springframework.web: ERROR
            org.hibernate: ERROR
